### ISSUE TITLE
Crash with apocalypse content pack on a server (1.12.2)

### ISSUE THREAD

**Issue by azery12356** [FlansMods/FlansMod#1082]
Hey , When I put the proto titan, the animation starts, then the server crash.
Can not restart the server without deleting the map

this is what the server tells me when it crashes:

 at com.flansmod.apocalypse.common.CommonProxyApocalypse.tick(CommonProxyApocalypse.java:142) ~[CommonProxyApocalypse.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_56_CommonProxyApocalypse_tick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[14:15:10] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[14:15:10] [Server thread/ERROR] [FML]: 0: NORMAL
[14:15:10] [Server thread/ERROR] [FML]: 1: ASM: com.flansmod.common.CommonTickHandler@7816a2f4 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:15:10] [Server thread/ERROR] [FML]: 2: ASM: net.minecraftforge.common.ForgeInternalHandler@f47a69b onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:15:10] [Server thread/ERROR] [FML]: 3: ASM: com.flansmod.apocalypse.common.CommonProxyApocalypse@641358b0 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[14:15:10] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: com.flansmod.apocalypse.common.entity.EntityNukeDrop.func_184227_b(D)V
        at com.flansmod.apocalypse.common.entity.EntityNukeDrop.<init>(EntityNukeDrop.java:19) ~[EntityNukeDrop.class:?]
        at com.flansmod.apocalypse.common.entity.EntityNukeDrop.<init>(EntityNukeDrop.java:27) ~[EntityNukeDrop.class:?]
        at com.flansmod.apocalypse.common.CommonProxyApocalypse.tick(CommonProxyApocalypse.java:142) ~[CommonProxyApocalypse.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_56_CommonProxyApocalypse_tick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by ChrisLane** [comment]
Please follow the crash report template and provide the whole crash report.
