### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Uniter343** [FlansMods/FlansMod#1112]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 8/11/19 10:41 PM
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:537)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:488)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:223)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:730)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:537)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:488)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:223)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:730)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 319689096 bytes (304 MB) / 939524096 bytes (896 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version      | Source                        | Signature                                |
	|:------ |:------------------ |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft          | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJA | mcp                | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJA | FML                | 8.0.99.99    | forge-1.12.2-14.23.2.2611.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge              | 14.23.2.2611 | forge-1.12.2-14.23.2.2611.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | mercurius_updater  | 1.0          | MercuriusUpdater-1.12.2.jar   | None                                     |
	| UCHIJA | flansmod           | 5.5.2        | Flan's Mod-1.12.2-5.5.2.jar   | None                                     |
	| UCHIJA | flansmodapocalypse | 1.0          | Flan's Mod-1.12.2-5.5.2.jar   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.86' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2611
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Tissous Zombie Pack 1.13.2.zip (incompatible), AudioCraftV1.5.zip
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz

**Comment by ChrisLane** [comment]
Please let us know if you're able to reproduce the issue with the latest version from here: https://github.com/FlansMods/FlansMod/releases
