### ISSUE TITLE
Opening Fuel tab crashes the server

### ISSUE THREAD

**Issue by JustGamma** [FlansMods/FlansMod#1155]
java.lang.NullPointerException: The validated object is null
    at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
    at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
    at net.minecraft.util.NonNullList.add(SourceFile:56)
    at java.util.AbstractList.add(AbstractList.java:108)
    at net.minecraft.inventory.Container.getInventory(Container.java:63)
    at net.minecraft.inventory.Container.addListener(Container.java:52)
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:101)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
    at com.flansmod.common.network.PacketDriveableGUI.handleServerSide(PacketDriveableGUI.java:52)
    at com.flansmod.common.network.PacketHandler.handleServerPackets(PacketHandler.java:171)
    at com.flansmod.common.CommonTickHandler.tick(CommonTickHandler.java:54)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_420_CommonTickHandler_tick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

**Comment by JustGamma** [comment]
1.12.2 Forge 2838 [Addons: modern warfare, ye olde pack and the classic parts]

**Comment by Liruxo** [comment]
Please use the crash template and use a service like github gits to post the full crash log. And please supply the FlansMod version as we currently have 9 (!) different FlansMod versions for 1.12.2

**Comment by ChrisLane** [comment]
Closing issue until version details are provided.
