### ISSUE TITLE
Immediate crash upon giving any form on input when wielding an SMG

### ISSUE THREAD

**Issue by ghost** [FlansMods/FlansMod#1198]
**To Reproduce**
Steps to reproduce the crash:
1. Wield a pistol or SMG
2. Give any form of user input (mouse or keyboard)
3. 
4. 

**Screenshots**

N/A as my issue is a crash
**Versions (please complete the following information)**
 - Forge: 1.12.2-14.23.5.2847
 - Flan's Mod: 5.5.2&5.6.0-beta (tested both)

**Crash Log**

[crash-2020-04-25_01.09.56-client.txt](https://github.com/FlansMods/FlansMod/files/4532115/crash-2020-04-25_01.09.56-client.txt)
**Additional context**

As the title says, I receive an immediate crash upon giving any input when holding any SMG. I have tried completing a fresh install of forge and everything else in my .minecraft folder which had some success. I was able to fully use and interact with said weapons. However when changing specific optifine settings (I couldn't tell you what setting may/is responsible, as repetitive testing and enabling/disabling previously changed settings yielded the same result), that's when it led to the immediate "shutting down internal server" and then crash.

Now the actual error it throws doesn't make sense to me (I don't know how to code in Java so take that very lightly ahah). This is the error in plain text. I will upload a crash-log also. Maybe optifine is unsupported and i just never got the memo, or maybe a possible mod incompatibility? I'm really not sure. Thank you for taking your time to read this ---------

Description: Unexpected error

java.lang.IndexOutOfBoundsException: -97
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at com.flansmod.client.handlers.ClientEventHandler.checkMouseInput(ClientEventHandler.java:105)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_792_ClientEventHandler_checkMouseInput_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:273)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2275)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1800)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Liruxo** [comment]
You  have a lot of mods installed. I suspect one of those is screwing around with the vanilla keybind functionality, please try to replicate this bug with the lowest amount of mods possible. I dont think optifine has anything to do with this, as i regularly test optifine compatibility, but optifine in combination with other mods may cause issues
Please also include the key you bind the "Sneak Key" too, as this is the keybind causing issues

**Comment by ChrisLane** [comment]
Similar issue to #320 I believe. Something wacky with your keybindings as @Liruxo said

**Comment by ghost** [comment]
I apologise for my late response. It was indeed my crouch key bind. I have it as my 4th mouth side button. I remember running into issues with a version of flans before on a MC server, however the server dev fixed it himself, and that was due to my key bind. Thank you for your responses

**Comment by ChrisLane** [comment]
@Samchovski I've just noticed that there's a fix that's not in a beta yet that probably will have avoided your crashes. #1143 
I'll make a new beta now
