### ISSUE TITLE
Game crashes when placing anything from WW2 mod

### ISSUE THREAD

**Issue by Thesmexypotato** [FlansMods/FlansMod#1268]
**Describe the bug**

Whenever i place down literally anything from the WW2 vcontent pack (vehicles) for 1.12.2, my game instantly crashes and says 'game crashed whilst ticking entity.'

**To Reproduce**
Steps to reproduce the behaviour:
1. open minecraft forge  1.12.2 with the WW2 pack installed.
2. load world
3. place anything from the WW2 vehicles section
4. Game will crash (at least for me)

**Expected behaviour**

**Screenshots**

heres the crash report if needed.

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 8/2/20 5:39 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:391)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:391)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: flansmod:vehicle (com.flansmod.common.driveables.EntityVehicle)
	Entity ID: 609
	Entity Name: Bofors 40mm AA Gun
	Entity's Exact location: 336.50, 72.50, 269.50
	Entity's Block location: World: (336,72,269), Chunk: (at 0,4,13 in 21,16; contains blocks 336,0,256 to 351,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntitySeat['entity.Seat.name'/610, l='New World', x=336.50, y=72.50, z=269.50], EntityWheel['entity.Wheel.name'/611, l='New World', x=335.04, y=71.88, z=269.50], EntityWheel['entity.Wheel.name'/612, l='New World', x=335.82, y=71.88, z=270.79], EntityWheel['entity.Wheel.name'/613, l='New World', x=337.96, y=71.88, z=269.50], EntityWheel['entity.Wheel.name'/614, l='New World', x=337.18, y=71.88, z=268.21]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['matthewtg'/325, l='New World', x=335.22, y=72.03, z=270.12]]
	Chunk stats: ServerChunkCache: 1225 Drop: 0
	Level seed: -8160950609842947203
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (252,64,252), Chunk: (at 12,4,12 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10863 game time, 10863 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 2069 (now: false), thunder time: 90820 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1842987528 bytes (1757 MB) / 3288334336 bytes (3136 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 8, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version         | Source                                            | Signature                                |
	|:------ |:------------------ |:--------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2          | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                | 9.42            | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                | 8.0.99.99       | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2854    | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | flansmod           | 5.5.1           | Flan's Mod-1.12.2-5.5.1.jar                       | None                                     |
	| LCHIJA | flansmodapocalypse | 1.0             | Flan's Mod-1.12.2-5.5.1.jar                       | None                                     |
	| LCHIJA | worldedit          | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['matthewtg'/325, l='New World', x=335.22, y=72.03, z=270.12]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
**Versions (please complete the following information)**
 - Forge: release 1.12.2-forge-14.23.5.2854
 - Flan's Mod: for 1.12.2       [Official][1.12.2]World War II Pack

**Additional context**

**Comment by DubTheGrub** [comment]
Flan's Mod version 5.5.1? Isn't that a bit outdated?

**Comment by ChrisLane** [comment]
You're using an old version of the mod
https://github.com/FlansMods/FlansMod/releases

**Comment by Thesmexypotato** [comment]
> Flan's Mod version 5.5.1? Isn't that a bit outdated?

ah. i got it from the flansmod website... guess it hasnt been updated in a long time. also where do you find newer content packs if the website IS infact unupdated.

**Comment by ChrisLane** [comment]
Content pack creators are still able to post their content pack updates on the website whenever they like.
The official content pack updates are at the link I posted.

**Comment by Thesmexypotato** [comment]
> Content pack creators are still able to post their content pack updates on the website whenever they like.
> The official content pack updates are at the link I posted.

-- Entity being ticked --
Details:
	Entity Type: flansmod:vehicle (com.flansmod.common.driveables.EntityVehicle)
	Entity ID: 5606
	Entity Name: Challenger II
	Entity's Exact location: 194.50, 65.50, -50.50
	Entity's Block location: World: (194,65,-51), Chunk: (at 2,4,13 in 12,-4; contains blocks 192,0,-64 to 207,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntitySeat['entity.Seat.name'/5607, l='New World', x=194.50, y=65.50, z=-50.50], EntitySeat['entity.Seat.name'/5608, l='New World', x=194.50, y=65.50, z=-50.50], EntityWheel['entity.Wheel.name'/5609, l='New World', x=191.24, y=64.88, z=-52.45], EntityWheel['entity.Wheel.name'/5610, l='New World', x=191.38, y=64.88, z=-48.33], EntityWheel['entity.Wheel.name'/5611, l='New World', x=198.07, y=64.88, z=-48.56], EntityWheel['entity.Wheel.name'/5612, l='New World', x=197.93, y=64.88, z=-52.68]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

Even on a new world and with updated content packs and the updated mod... my world still crashes when placing an entity from the WW2 section :(

**Comment by ChrisLane** [comment]
Can you post the new full crash log please?

**Comment by Thesmexypotato** [comment]
---- Minecraft Crash Report ----
// You're mean.

Time: 8/4/20 8:31 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.flansmod.common.driveables.EntityVehicle.canThrust(EntityVehicle.java:607)
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:389)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.flansmod.common.driveables.EntityVehicle.canThrust(EntityVehicle.java:607)
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:389)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: flansmod:vehicle (com.flansmod.common.driveables.EntityVehicle)
	Entity ID: 594
	Entity Name: Challenger II
	Entity's Exact location: 194.50, 65.50, -49.50
	Entity's Block location: World: (194,65,-50), Chunk: (at 2,4,14 in 12,-4; contains blocks 192,0,-64 to 207,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntitySeat['entity.Seat.name'/595, l='New World', x=194.50, y=65.50, z=-49.50], EntitySeat['entity.Seat.name'/596, l='New World', x=194.50, y=65.50, z=-49.50], EntityWheel['entity.Wheel.name'/597, l='New World', x=191.51, y=64.88, z=-51.84], EntityWheel['entity.Wheel.name'/598, l='New World', x=191.14, y=64.88, z=-47.73], EntityWheel['entity.Wheel.name'/599, l='New World', x=197.80, y=64.88, z=-47.13], EntityWheel['entity.Wheel.name'/600, l='New World', x=198.17, y=64.88, z=-51.24]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['matthewtg'/351, l='New World', x=191.87, y=64.00, z=-50.14]]
	Chunk stats: ServerChunkCache: 961 Drop: 0
	Level seed: -4474536742331542803
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (176,64,-52), Chunk: (at 0,4,12 in 11,-4; contains blocks 176,0,-64 to 191,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1948 game time, 1948 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 88492 (now: false), thunder time: 30034 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 777443920 bytes (741 MB) / 2147483648 bytes (2048 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version         | Source                                            | Signature                                |
	|:------ |:--------- |:--------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2          | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp       | 9.42            | minecraft.jar                                     | None                                     |
	| LCHIJA | FML       | 8.0.99.99       | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2854    | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | flansmod  | 5.6.0-beta.8    | Flan.s.Mod-1.12.2-5.6.0-beta.8.jar                | None                                     |
	| LCHIJA | worldedit | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['matthewtg'/351, l='New World', x=191.87, y=64.00, z=-50.14]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Thesmexypotato** [comment]
> Can you post the new full crash log please?

---- Minecraft Crash Report ----
// You're mean.

Time: 8/4/20 8:31 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.flansmod.common.driveables.EntityVehicle.canThrust(EntityVehicle.java:607)
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:389)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.flansmod.common.driveables.EntityVehicle.canThrust(EntityVehicle.java:607)
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:389)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: flansmod:vehicle (com.flansmod.common.driveables.EntityVehicle)
	Entity ID: 594
	Entity Name: Challenger II
	Entity's Exact location: 194.50, 65.50, -49.50
	Entity's Block location: World: (194,65,-50), Chunk: (at 2,4,14 in 12,-4; contains blocks 192,0,-64 to 207,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntitySeat['entity.Seat.name'/595, l='New World', x=194.50, y=65.50, z=-49.50], EntitySeat['entity.Seat.name'/596, l='New World', x=194.50, y=65.50, z=-49.50], EntityWheel['entity.Wheel.name'/597, l='New World', x=191.51, y=64.88, z=-51.84], EntityWheel['entity.Wheel.name'/598, l='New World', x=191.14, y=64.88, z=-47.73], EntityWheel['entity.Wheel.name'/599, l='New World', x=197.80, y=64.88, z=-47.13], EntityWheel['entity.Wheel.name'/600, l='New World', x=198.17, y=64.88, z=-51.24]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['matthewtg'/351, l='New World', x=191.87, y=64.00, z=-50.14]]
	Chunk stats: ServerChunkCache: 961 Drop: 0
	Level seed: -4474536742331542803
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (176,64,-52), Chunk: (at 0,4,12 in 11,-4; contains blocks 176,0,-64 to 191,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1948 game time, 1948 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 88492 (now: false), thunder time: 30034 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 777443920 bytes (741 MB) / 2147483648 bytes (2048 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version         | Source                                            | Signature                                |
	|:------ |:--------- |:--------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2          | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp       | 9.42            | minecraft.jar                                     | None                                     |
	| LCHIJA | FML       | 8.0.99.99       | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2854    | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | flansmod  | 5.6.0-beta.8    | Flan.s.Mod-1.12.2-5.6.0-beta.8.jar                | None                                     |
	| LCHIJA | worldedit | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['matthewtg'/351, l='New World', x=191.87, y=64.00, z=-50.14]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Coloradohusky** [comment]
I'm having this same issue, playing on the latest version (beta-10) with WW2 installed.
