### ISSUE TITLE
1.12.2 doesnt work at all

### ISSUE THREAD

**Issue by Kayanchi** [FlansMods/FlansMod#1320]
Hello,
I have many problems with the 1.12.2 flans mod:
-Some wepons crash the game if held in hand     Examples: MP7
-The Sentry Gun spawns 2 blocks above ground
-Many moddels are "special"                   Examples: Leopard tank, WW2 handgrenade
-I cant shoot as the driver the mg/secondary wepon (I tried left click, right click and b)
![2020-11-19_13 45 51](https://user-images.githubusercontent.com/66892428/99679972-d99a2000-2a7c-11eb-81f9-1e3968e5df4e.png)
![2020-11-19_13 42 44](https://user-images.githubusercontent.com/66892428/99679988-ddc63d80-2a7c-11eb-90f2-0079d1ff4df1.png)

**Comment by Kayanchi** [comment]
This is a crash report from a wepon moddel:
---- Minecraft Crash Report ----
// Sorry :(

Time: 11/19/20 1:43 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:544)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:262)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at com.flansmod.client.ClientEventHandler.CheckForOffHandWeaponSwitch(ClientEventHandler.java:128)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_66_ClientEventHandler_CheckForOffHandWeaponSwitch_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:245)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1798)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:544)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:262)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at com.flansmod.client.ClientEventHandler.CheckForOffHandWeaponSwitch(ClientEventHandler.java:128)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_66_ClientEventHandler_CheckForOffHandWeaponSwitch_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:245)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Kayanosenpai'/2394, l='MpServer', x=117.76, y=71.00, z=260.43]]
	Chunk stats: MultiplayerChunkCache: 525, 525
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (120,64,248), Chunk: (at 8,4,8 in 7,15; contains blocks 112,0,240 to 127,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2266 game time, 2266 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 109 total; [EntityItem['item.tile.sapling.oak'/6144, l='MpServer', x=157.66, y=71.00, z=286.94], EntityCreeper['Creeper'/6157, l='MpServer', x=112.50, y=42.00, z=213.50], EntityCreeper['Creeper'/6160, l='MpServer', x=94.50, y=28.00, z=239.50], EntityCreeper['Creeper'/6161, l='MpServer', x=48.50, y=18.00, z=306.50], EntityBat['Bat'/6173, l='MpServer', x=38.42, y=25.35, z=184.15], EntityBat['Bat'/6174, l='MpServer', x=98.46, y=25.00, z=303.36], EntitySpider['Spider'/6190, l='MpServer', x=39.50, y=25.00, z=186.50], EntityCow['Cow'/56, l='MpServer', x=47.50, y=66.00, z=259.50], EntityCow['Cow'/57, l='MpServer', x=49.59, y=64.00, z=264.20], EntityCow['Cow'/58, l='MpServer', x=51.50, y=66.00, z=255.50], EntityCow['Cow'/59, l='MpServer', x=49.78, y=67.00, z=247.59], EntityPig['Pig'/60, l='MpServer', x=43.50, y=67.00, z=260.26], EntityPig['Pig'/61, l='MpServer', x=42.50, y=67.00, z=256.50], EntityPig['Pig'/62, l='MpServer', x=40.50, y=67.00, z=257.50], EntityPig['Pig'/63, l='MpServer', x=44.50, y=67.00, z=259.50], EntityCow['Cow'/64, l='MpServer', x=83.50, y=75.00, z=326.50], EntityCow['Cow'/65, l='MpServer', x=76.45, y=78.00, z=324.55], EntityCow['Cow'/66, l='MpServer', x=78.81, y=78.00, z=325.45], EntityCow['Cow'/67, l='MpServer', x=77.56, y=78.00, z=324.55], EntityHorse['Horse'/72, l='MpServer', x=117.50, y=64.00, z=309.50], EntityHorse['Horse'/73, l='MpServer', x=117.50, y=64.00, z=309.50], EntityHorse['Horse'/74, l='MpServer', x=114.50, y=67.00, z=305.50], EntityHorse['Horse'/78, l='MpServer', x=142.30, y=65.00, z=225.71], EntityHorse['Horse'/79, l='MpServer', x=146.01, y=65.00, z=232.61], EntityHorse['Horse'/80, l='MpServer', x=138.93, y=65.00, z=236.07], EntityHorse['Horse'/81, l='MpServer', x=141.12, y=65.00, z=226.85], EntityPig['Pig'/82, l='MpServer', x=131.34, y=64.00, z=231.51], EntityPig['Pig'/83, l='MpServer', x=130.49, y=69.12, z=242.66], EntityPig['Pig'/84, l='MpServer', x=120.78, y=72.00, z=253.50], EntityPig['Pig'/85, l='MpServer', x=143.22, y=66.00, z=239.49], EntityHorse['Horse'/86, l='MpServer', x=126.00, y=65.00, z=290.23], EntityHorse['Horse'/87, l='MpServer', x=125.30, y=65.00, z=289.06], EntityCow['Cow'/88, l='MpServer', x=131.50, y=63.00, z=334.50], EntityChicken['Chicken'/90, l='MpServer', x=136.50, y=64.00, z=303.50], EntityChicken['Chicken'/91, l='MpServer', x=137.50, y=64.00, z=307.50], EntityChicken['Chicken'/92, l='MpServer', x=139.50, y=66.00, z=306.50], EntityChicken['Chicken'/93, l='MpServer', x=141.50, y=67.00, z=304.50], EntityCow['Cow'/108, l='MpServer', x=169.83, y=63.00, z=221.79], EntityCow['Cow'/109, l='MpServer', x=173.50, y=63.00, z=228.50], EntityCow['Cow'/110, l='MpServer', x=177.50, y=63.00, z=226.50], EntityCow['Cow'/111, l='MpServer', x=179.50, y=63.00, z=225.50], EntityCow['Cow'/112, l='MpServer', x=191.53, y=64.00, z=195.15], EntityCow['Cow'/114, l='MpServer', x=195.50, y=64.00, z=186.50], EntityCow['Cow'/115, l='MpServer', x=195.30, y=64.00, z=191.75], EntityCow['Cow'/116, l='MpServer', x=192.50, y=63.00, z=223.50], EntityCow['Cow'/117, l='MpServer', x=191.50, y=64.00, z=221.50], EntityCow['Cow'/118, l='MpServer', x=191.50, y=64.00, z=221.50], EntityCow['Cow'/119, l='MpServer', x=192.50, y=66.00, z=217.50], EntityZombie['Zombie'/6264, l='MpServer', x=97.50, y=26.00, z=301.50], EntityZombie['Zombie'/6265, l='MpServer', x=91.74, y=27.00, z=309.49], EntityCreeper['Creeper'/6266, l='MpServer', x=96.50, y=26.00, z=299.50], EntitySpider['Spider'/4345, l='MpServer', x=158.57, y=20.00, z=313.52], EntitySkeleton['Skeleton'/6408, l='MpServer', x=90.50, y=28.00, z=309.50], EntitySkeleton['Skeleton'/6437, l='MpServer', x=96.50, y=35.00, z=208.50], EntitySkeleton['Skeleton'/6438, l='MpServer', x=96.50, y=35.00, z=209.50], EntitySkeleton['Skeleton'/6462, l='MpServer', x=183.50, y=33.00, z=225.50], EntityZombie['Zombie'/6472, l='MpServer', x=98.50, y=31.00, z=325.50], EntityZombie['Zombie'/6473, l='MpServer', x=98.50, y=31.00, z=322.50], EntityZombie['Zombie'/4432, l='MpServer', x=109.50, y=26.00, z=231.50], EntityCreeper['Creeper'/6485, l='MpServer', x=92.50, y=19.00, z=182.50], EntityPlayerSP['Kayanosenpai'/2394, l='MpServer', x=117.76, y=71.00, z=260.43], EntitySpider['Spider'/6537, l='MpServer', x=110.50, y=19.00, z=339.50], EntitySpider['Spider'/6538, l='MpServer', x=114.50, y=19.00, z=337.50], EntityBat['Bat'/6557, l='MpServer', x=81.62, y=45.04, z=237.45], EntitySkeleton['Skeleton'/6591, l='MpServer', x=54.50, y=15.00, z=184.50], EntityCreeper['Creeper'/6592, l='MpServer', x=59.34, y=15.00, z=183.74], EntityCreeper['Creeper'/6593, l='MpServer', x=189.50, y=32.00, z=208.50], EntityCreeper['Creeper'/6595, l='MpServer', x=177.50, y=39.00, z=232.50], EntityItem['item.tile.sapling.oak'/6600, l='MpServer', x=158.30, y=72.00, z=286.41], EntitySkeleton['Skeleton'/4591, l='MpServer', x=133.50, y=43.00, z=243.50], EntitySpider['Spider'/4615, l='MpServer', x=97.50, y=33.00, z=335.50], EntityItem['item.item.seeds'/4673, l='MpServer', x=162.36, y=67.00, z=313.65], EntitySkeleton['Skeleton'/4918, l='MpServer', x=112.50, y=28.00, z=233.50], EntityZombie['Zombie'/2885, l='MpServer', x=112.25, y=28.00, z=334.98], EntityAAGun['entity.AAGun.name'/4958, l='MpServer', x=114.50, y=74.00, z=254.50], EntityBat['Bat'/5068, l='MpServer', x=109.68, y=31.64, z=231.04], EntityCreeper['Creeper'/5100, l='MpServer', x=91.50, y=19.00, z=184.50], EntityBat['Bat'/5196, l='MpServer', x=108.43, y=41.10, z=247.70], EntitySpider['Spider'/5240, l='MpServer', x=117.48, y=29.00, z=292.54], EntityCreeper['Creeper'/5297, l='MpServer', x=111.50, y=44.00, z=217.50], EntityBat['Bat'/5310, l='MpServer', x=158.13, y=23.69, z=303.40], EntityAAGun['entity.AAGun.name'/5392, l='MpServer', x=117.50, y=74.00, z=252.50], EntityZombie['Zombie'/5419, l='MpServer', x=106.50, y=28.00, z=326.50], EntitySkeleton['Skeleton'/5420, l='MpServer', x=107.50, y=28.00, z=328.50], EntitySpider['Spider'/5466, l='MpServer', x=111.50, y=13.00, z=182.50], EntityBat['Bat'/5503, l='MpServer', x=86.75, y=46.86, z=236.75], EntityCreeper['Creeper'/3497, l='MpServer', x=85.50, y=15.00, z=184.50], EntityCreeper['Creeper'/3498, l='MpServer', x=84.50, y=15.00, z=184.50], EntityCreeper['Creeper'/5588, l='MpServer', x=55.50, y=15.00, z=184.50], EntityBat['Bat'/5716, l='MpServer', x=112.25, y=26.10, z=311.25], EntityCreeper['Creeper'/5735, l='MpServer', x=180.82, y=34.00, z=223.50], EntityZombie['Zombie'/5815, l='MpServer', x=125.82, y=63.00, z=182.50], EntityBat['Bat'/3797, l='MpServer', x=114.59, y=28.10, z=316.25], EntitySkeleton['Skeleton'/5905, l='MpServer', x=87.50, y=49.00, z=247.50], EntityBat['Bat'/5914, l='MpServer', x=111.47, y=28.98, z=336.24], EntityBat['Bat'/5915, l='MpServer', x=105.84, y=32.34, z=332.00], EntityItem['item.tile.doublePlant.rose'/5927, l='MpServer', x=86.13, y=63.00, z=234.70], EntityCreeper['Creeper'/5929, l='MpServer', x=83.50, y=33.00, z=308.50], EntitySkeleton['Skeleton'/5930, l='MpServer', x=78.52, y=33.00, z=313.22], EntityCreeper['Creeper'/5931, l='MpServer', x=80.50, y=33.00, z=310.50], EntityCreeper['Creeper'/3964, l='MpServer', x=78.70, y=24.24, z=221.30], EntitySkeleton['Skeleton'/6013, l='MpServer', x=165.50, y=22.00, z=314.50], EntityCreeper['Creeper'/6029, l='MpServer', x=114.50, y=39.00, z=207.50], EntityBat['Bat'/6075, l='MpServer', x=159.38, y=24.45, z=303.84], EntitySpider['Spider'/6113, l='MpServer', x=109.50, y=28.00, z=330.50], EntitySpider['Spider'/6115, l='MpServer', x=107.50, y=28.00, z=329.50], EntitySpider['Spider'/6116, l='MpServer', x=107.50, y=28.00, z=331.50], EntityEnderman['Enderman'/6117, l='MpServer', x=118.51, y=29.00, z=341.40], EntityBat['Bat'/6138, l='MpServer', x=113.08, y=14.49, z=247.70]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_265, Eclipse OpenJ9
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 7 amd64-64-Bit Compressed References 20200728_776 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01), Eclipse OpenJ9
	Memory: 53360800 bytes (50 MB) / 514850816 bytes (491 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 11 total; -Xoptionsfile=C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-openj9\jre\bin\compressedrefs\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2624 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                 | Version      | Source                        | Signature                                |
	|:--------- |:------------------ |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft          | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp                | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML                | 8.0.99.99    | forge-1.12.2-14.23.2.2624.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge              | 14.23.2.2624 | forge-1.12.2-14.23.2.2624.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater  | 1.0          | MercuriusUpdater-1.12.2.jar   | None                                     |
	| UCHIJAAAA | flansmod           | 5.5.2        | Flan's Mod-1.12.2-5.5.2.jar   | None                                     |
	| UCHIJAAAA | flansmodapocalypse | 1.0          | Flan's Mod-1.12.2-5.5.2.jar   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4414' Renderer: 'Intel(R) HD Graphics 4600'
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2624
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 10.18.14.4414, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Kayano mix
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz

**Comment by Kayanchi** [comment]
And sometimes I get a crash if I scroll too quickly through a hotbar full of wepons
