### ISSUE TITLE
flans Mod crashing on startup with forge

### ISSUE THREAD

**Issue by 05-1** [FlansMods/FlansMod#1444]
the error is as follows:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  MovingWorldCore (movingworld-1.12-6.353-full.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.17.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  FutureMC (future-mc-0.2.9.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2 (1).jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 5/30/22 3:48 PM
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:596)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:249)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:596)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:249)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1631870488 bytes (1556 MB) / 4697620480 bytes (4480 MB) up to 21474836480 bytes (20480 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx20G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version             | Source                                            | Signature                                |
	|:------ |:-------------------------------------------- |:------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2              | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                                          | 9.42                | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99           | forge-1.12.2-14.23.5.2859.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2859        | forge-1.12.2-14.23.5.2859.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit                                    | 1.3.3-1.12          | minecraft.jar                                     | None                                     |
	| LCHIJA | micdoodlecore                                |                     | minecraft.jar                                     | None                                     |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                     | minecraft.jar                                     | None                                     |
	| LCHIJA | techguns_core                                | 1.12.2-1.0          | minecraft.jar                                     | None                                     |
	| LCHIJA | mantle                                       | 1.12-1.3.3.55       | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LCHIJA | endercore                                    | 1.12.2-0.5.76       | EnderCore-1.12.2-0.5.76.jar                       | None                                     |
	| LCHIJA | jei                                          | 4.16.1.301          | jei_1.12.2-4.16.1.301.jar                         | None                                     |
	| LCHIJA | enderio                                      | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | enderiointegrationtic                        | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | quark                                        | r1.6-177            | Quark-r1.6-177.jar                                | None                                     |
	| LCHIJA | tconstruct                                   | 1.12.2-2.13.0.183   | TConstruct-1.12.2-2.13.0.183.jar                  | None                                     |
	| LCHIJA | galacticraftcore                             | 4.0.2.280           | GalacticraftCore-1.12.2-4.0.2.280.jar             | None                                     |
	| LCHIJA | galacticraftplanets                          | 4.0.2.280           | Galacticraft-Planets-1.12.2-4.0.2.280.jar         | None                                     |
	| LCHIJA | asmodeuscore                                 | 0.0.28              | AsmodeusCore-1.12.2-0.0.28.jar                    | None                                     |
	| LCHIJA | autoreglib                                   | 1.3-32              | AutoRegLib-1.3-32.jar                             | None                                     |
	| LCHIJA | bettercaves                                  | 1.12.2              | bettercaves-1.12.2-2.0.2.jar                      | None                                     |
	| LCHIJA | better_diving                                | 1.5.8               | BetterDiving-1.12.2-1.5.8.jar                     | None                                     |
	| LCHIJA | biomesoplenty                                | 7.0.1.2444          | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar     | None                                     |
	| LCHIJA | codechickenlib                               | 3.2.3.358           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | craftstudioapi                               | 1.0.0               | CraftStudio-1.0.0.93-mc1.12-alpha.jar             | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.353          | movingworld-1.12-6.353-full.jar                   | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@       | davincisvessels-1.12-6.340-full.jar               | None                                     |
	| LCHIJA | enderiobase                                  | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | enderioconduits                              | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics            | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | enderioconduitsopencomputers                 | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | refinedstorage                               | 1.6.16              | refinedstorage-1.12.2.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | enderioconduitsrefinedstorage                | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | enderiointegrationforestry                   | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | enderiointegrationticlate                    | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | enderioinvpanel                              | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | enderiomachines                              | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | enderiopowertools                            | 5.3.70              | EnderIO-1.12.2-5.3.70.jar                         | None                                     |
	| LCHIJA | flansmod                                     | 5.10.0              | Flan's+Mod-1.12.2-5.10.0.jar                      | None                                     |
	| LCHIJA | forgelin                                     | 1.8.3               | Forgelin-1.8.3.jar                                | None                                     |
	| LCHIJA | futuremc                                     | 0.2.6               | future-mc-0.2.9.jar                               | None                                     |
	| LCHIJA | galaxyspace                                  | 2.0.17              | GalaxySpace-1.12.2-2.0.17.jar                     | None                                     |
	| LCHIJA | hbm                                          | hbm-1.6.4.2A-1.12.2 | hbm-1.6.4a-Gv2.jar                                | None                                     |
	| LCHIJA | waila                                        | 1.8.26              | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCHIJA | icbmclassic                                  | 1.12.2-4.0.1.75     | ICBM-classic-1.12.2-4.0.1b75.jar                  | None                                     |
	| LCHIJA | nei                                          | 2.4.3               | NotEnoughItems-1.12.2-2.4.3.245-universal (1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | omlib                                        | 3.1.5-256           | omlib-1.12.2-3.1.5-256.jar                        | None                                     |
	| LCHIJA | openmodularturrets                           | 3.1.14-382          | openmodularturrets-1.12.2-3.1.14-382.jar          | None                                     |
	| LCHIJA | reccomplex                                   | 1.4.8.2             | RecurrentComplex-1.4.8.2.jar                      | None                                     |
	| LCHIJA | roguelike                                    | 1.8.0               | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| LCHIJA | techguns                                     | 2.0.2.0             | techguns-1.12.2-2.0.2.0_pre3.2 (1).jar            | None                                     |
	| LCHIJA | tektopia                                     | 1.1.0               | tektopia-1.1.0.jar                                | None                                     |
	| LCHIJA | worldedit                                    | 6.1.10              | worldedit-forge-mc1.12.2-6.1.10-dist.jar          | None                                     |
	| LCHIJA | rtg                                          | 6.1.0.0-snapshot.1  | RTG-1.12.2-6.1.0.0-snapshot.1.jar                 | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
GSHooksLoader (GalaxySpace-1.12.2-2.0.17.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
FutureMC (future-mc-0.2.9.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2 (1).jar)
  techguns.core.TechgunsASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.15' Renderer: 'NVIDIA GeForce GTX 1070/PCIe/SSE2'
	Ender IO: No known problems detected.
	Authlib is : /C:/Users/dvorn_zup1y2c/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.15, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs:  2 lFurf b lSky  5 lReborn  8 lFL 8 l[ 71.4.2 8 l].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

**Comment by 05-1** [comment]
outdated mods/contentpacks pardon
