### ISSUE TITLE
When i start my mine server i have this crash-report.

### ISSUE THREAD

**Issue by quattro982** [FlansMods/FlansMod#1445]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  weaponlib (mw_2.0-0.4.6.2_mc1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 01.06.22 11:31
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Flan's Mod: Apocalypse (flansmodapocalypse)
Caused by: java.lang.NullPointerException
	at com.flansmod.apocalypse.common.FlansModApocalypse.preInit(FlansModApocalypse.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_321, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 369820704 bytes (352 MB) / 2022703104 bytes (1929 MB) up to 2022703104 bytes (1929 MB)
	JVM Flags: 2 total; -Xmx2024M -Xms2024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                          | Signature                                |
	|:----- |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCH   | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
	| LCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2859             | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore        |                          | minecraft.jar                                   | None                                     |
	| LCH   | foamfixcore          | 7.7.4                    | minecraft.jar                                   | None                                     |
	| LCH   | obfuscate            | 0.4.2                    | minecraft.jar                                   | None                                     |
	| LCH   | opencomputers|core   | 1.7.5.192                | minecraft.jar                                   | None                                     |
	| LCH   | securitycraft        | v1.8.14                  | [1.12.2]+SecurityCraft+v1.8.14.jar              | None                                     |
	| LCH   | blockcraftery        | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                  | None                                     |
	| LCH   | chiseled_me          | 1.12-3.0.0.0-git-e5ce416 | chiseled-me-1.12-3.0.0.0-git-e5ce416.jar        | c677c954974252994736eb15e855e1e6fc5a2e62 |
	| LCH   | customnpcs           | 1.12                     | CustomNPCs_1.12.2-(05Jul20).jar                 | None                                     |
	| LCH   | cxlibrary            | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                      | None                                     |
	| LCH   | props                | 2.6.3.7                  | Decocraft-2.6.3.7_1.12.2.jar                    | None                                     |
	| LCH   | cdm                  | 0.4.1                    | device-mod-0.4.1-1.12.2.jar                     | None                                     |
	| LCH   | foamfix              | 0.10.14-1.12.2           | foamfix-0.10.14-1.12.2.jar                      | None                                     |
	| LCH   | cfm                  | 6.3.1                    | furniture-6.3.1-1.12.2.jar                      | None                                     |
	| LCH   | galacticraftcore     | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280.jar           | None                                     |
	| LCH   | galacticraftplanets  | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280.jar       | None                                     |
	| LCH   | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCH   | mts                  | 21.1.0                   | Immersive+Vehicles-1.12.2-21.1.0.jar            | None                                     |
	| LCH   | journeymap           | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                     | None                                     |
	| LCH   | malisiscore          | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                    | None                                     |
	| LCH   | malisisblocks        | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                  | None                                     |
	| LCH   | malisisdoors         | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| LCH   | moneysandothers      | 0.2.3                    | MAO_1.12.2_v0.2.3.jar                           | None                                     |
	| LCH   | mw                   | 0.4.6.2                  | mw_2.0-0.4.6.2_mc1.12.2.jar                     | None                                     |
	| LCH   | opencomputers        | 1.7.5.192                | OpenComputers-MC1.12.2-1.7.5.192.jar            | None                                     |
	| LCH   | phonesalpha          | v1.11                    | pa1.11.jar                                      | None                                     |
	| LCH   | examplemod           | 1.0                      | Soviet+Flan's+Mod-1.12.2-5.5.2.1.jar            | None                                     |
	| LCH   | flansmod             | 5.5.2                    | Soviet+Flan's+Mod-1.12.2-5.5.2.1.jar            | None                                     |
	| LCE   | flansmodapocalypse   | 1.0                      | Soviet+Flan's+Mod-1.12.2-5.5.2.1.jar            | None                                     |
	| LC    | unuparts             | 5.1.2                    | UNU+Parts+Pack+[MTS]+1.12.2-21.1.0-5.1.2.jar    | None                                     |
	| LC    | unucivil             | 5.3.0                    | UNU+Civilian+Pack+[MTS]+1.12.2-21.1.0-5.3.0.jar | None                                     |
	| LC    | vehicle              | 0.44.1                   | vehicle-mod-0.44.1-1.12.2.jar                   | None                                     |
	| LC    | worldedit            | 6.1.10                   | worldedit-forge-mc1.12.2-6.1.10-dist.jar        | None                                     |
	| LC    | immersiveengineering | 0.12-98                  | ImmersiveEngineering-0.12-98.jar                | None                                     |
	| LC    | matteroverdrive      | 0.7.0.0                  | MatterOverdrive-1.12.2-0.7.1.0-universal.jar    | None                                     |
	| LC    | mysticallib          | 1.12.2-1.13.0            | mysticallib-1.12.2-1.13.0.jar                   | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
weaponlib (mw_2.0-0.4.6.2_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

plss help

**Comment by pixelrider2000** [comment]
I havn't painstakingly scrutinized the error, but I would try to remove the apocalypse content pack from your 'flan-folder' and restart the server. Make sure to create a backup of your world if you care about it.
