### ISSUE TITLE
The problem has been solved through self-developed plug-ins

### ISSUE THREAD

**Issue by zhanying233** [FlansMods/FlansMod#1463]
Please delete this Issuse

**Comment by zhanying233** [comment]
[20:36:44] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid null NBT value with key null
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: Invalid null NBT value with key null
	at net.minecraft.nbt.NBTTagCompound.func_74782_a(NBTTagCompound.java:80) ~[fy.class:?]
	at com.flansmod.common.guns.InventoryGunModTable.func_70296_d(InventoryGunModTable.java:62) ~[InventoryGunModTable.class:?]
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:76) ~[agr.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:71) ~[agr.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:407) ~[afr.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2223) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by zhanying233** [comment]
It looks like the problem is caused by NBT. Do you have any suggestions on how to fix it?
