### ISSUE TITLE
Missing Texture Error (java.io.FileNotFoundException)

### ISSUE THREAD

**Issue by XxCoolGamesxX** [FlansMods/FlansMod#645]
Hey,
Not use the Optifine and not use a Resource Pack. Only of Minecraft
Use: FLANS-4.9.0.
Forge: 10.13.2.1291

Here error:
```
[17:43:21] [Client thread/ERROR]: Using missing texture, unable to load flansmod:textures/items/MTAR_Green.png
java.io.FileNotFoundException: flansmod:textures/items/MTAR_Green.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
	at shadersmodcore.client.ShadersTex.loadResource(ShadersTex.java:998) ~[ShadersTex.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52) [bqf.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:538) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

**Comment by ChrisLane** [comment]
This has already been fixed for the next mod version which has yet to be released.

**Comment by XxCoolGamesxX** [comment]
Cool, Thank for info.

**Comment by darthvader45** [comment]
Same error with 5.5.2, which is the latest version available from the main site.

**Comment by ChrisLane** [comment]
@darthvader45 https://github.com/FlansMods/FlansMod/releases

**Comment by darthvader45** [comment]
Thanks for the new release.  Hopefully it goes up on the official site, or maybe get something going on CurseForge?
