### ISSUE TITLE
Constant crashing at startup

### ISSUE THREAD

**Issue by protoverz** [FlansMods/FlansMod#730]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PlayerAPIPlugin (PlayerAPI-1.8-1.3.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 8/16/15 6:11 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.client.renderer.texture.TextureMap.<init>(Ljava/lang/String;Z)V
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9840325896 bytes (9384 MB) / 10290200576 bytes (9813 MB) up to 10290200576 bytes (9813 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -Xms10G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1486 Optifine OptiFine_1.8_HD_U_D3 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1486.jar) 
	UCH	Forge{11.14.3.1486} [Minecraft Forge] (forge-1.8-11.14.3.1486.jar) 
	UCH	PlayerAPI{1.3} [Player API] (minecraft.jar) 
	UCH	bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
	UCH	ArmorStatusHUD{1.8} [ArmorStatusHUD] ([1.8]ArmorStatusHUD-client-1.29.jar) 
	UCH	StatusEffectHUD{1.8} [StatusEffectHUD] ([1.8]StatusEffectHUD-client-1.27.jar) 
	UCH	flansmod{5.0} [Flan's Mod] (Flan's Mod-1.8-5.0.jar) 
	UCH	flansmodapocalypse{1.0} [Flan's Mod: Apocalypse] (Flan's Mod Apocalypse-1.8-1.0.jar) 
	UCH	ToggleSneak{3.1.1} [ToggleSneak] (ToggleSneak-(1.8)-v3.1.1.jar) 
	UCH	XaeroMinimap{1.4.9} [Xaero's Minimap] (xaeros_minimap_v1.4.9_1.8_Forge.jar) 
	Loaded coremods (and transformers): 
PlayerAPIPlugin (PlayerAPI-1.8-1.3.jar)
  api.player.forge.PlayerAPITransformer
	Launched Version: 1.8-Forge11.14.3.1486
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6530D GL version 4.5.13397 Compatibility Profile Context 15.200.1046.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [nikeboom's faithful]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by karlthepagan** [comment]
Upgrade to OptiFine 1.8.0 HD U F8
