### ISSUE TITLE
plz tell me how to fix if

### ISSUE THREAD

**Issue by danielplw2** [FlansMods/FlansMod#780]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 16年1月21日 上午3:35
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:381)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:381)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)

-- Entity being ticked --
Details:
	Entity Type: Vehicle (com.flansmod.common.driveables.EntityVehicle)
	Entity ID: 6393
	Entity Name: Buggy
	Entity's Exact location: 844.50, 88.50, 820.50
	Entity's Block location: 844.00,88.00,820.00 - World: (844,88,820), Chunk: (at 12,5,4 in 52,51; contains blocks 832,0,816 to 847,255,831), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
	Level name: 新的世界
	All players: 1 total; [EntityPlayerMP['Yuki0430'/259, l='新的世界', x=845.64, y=87.00, z=824.02]]
	Chunk stats: ServerChunkCache: 1001 Drop: 0
	Level seed: -2308496436141251746
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 862.00,64.00,846.00 - World: (862,64,846), Chunk: (at 14,4,14 in 53,52; contains blocks 848,0,832 to 863,255,847), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 1434 game time, 1434 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 133354 (now: false), thunder time: 158112 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 315533176 bytes (300 MB) / 835284992 bytes (796 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1474 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1474.jar) 
	UCHIJAAAA	Forge{11.14.3.1474} [Minecraft Forge] (forge-1.8-11.14.3.1474.jar) 
	UCHIJAAAA	flansmod{5.0} [Flan's Mod] (Flan's Mod-1.8-5.0.jar) 
	UCHIJAAAA	flansmodapocalypse{1.0} [Flan's Mod: Apocalypse] (Flan's Mod Apocalypse-1.8-1.0.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Yuki0430'/259, l='新的世界', x=845.64, y=87.00, z=824.02]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Andrae05** [comment]
I think you have the same probleme as me but srry i dont know how to fix
