### ISSUE TITLE
Ticking Memory Connection crash Flans Fleet Pack

### ISSUE THREAD

**Issue by Creepy11** [FlansMods/FlansMod#815]
Hello. 
I'm playing with flans mod 1.7.10 version 4.10.0 on forge 10.13.4.1614 with fleet pack 1.0 content pack and when i place a vehicle my game crash and i get this crashlog:
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 13.06.16 12:38
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at com.flansmod.common.driveables.DriveableType.getDriveable(DriveableType.java:544)
	at com.flansmod.common.driveables.DriveableData.readFromNBT(DriveableData.java:45)
	at com.flansmod.common.driveables.DriveableData.<init>(DriveableData.java:34)
	at com.flansmod.common.driveables.ItemVehicle.getData(ItemVehicle.java:159)
	at com.flansmod.common.driveables.ItemVehicle.func_77659_a(ItemVehicle.java:136)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.flansmod.common.driveables.DriveableType.getDriveable(DriveableType.java:544)
	at com.flansmod.common.driveables.DriveableData.readFromNBT(DriveableData.java:45)
	at com.flansmod.common.driveables.DriveableData.<init>(DriveableData.java:34)
	at com.flansmod.common.driveables.ItemVehicle.getData(ItemVehicle.java:159)
	at com.flansmod.common.driveables.ItemVehicle.func_77659_a(ItemVehicle.java:136)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@6d687c2e
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 259956248 bytes (247 MB) / 546992128 bytes (521 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 9, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D4 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.94} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.94-universal.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) 
	UCHIJAAAA	LunatriusCore{1.1.0.8} [LunatriusCore] (LunatriusCore-1.7.10.jar) 
	UCHIJAAAA	Schematica{1.7.0.80} [Schematica] (Schematica-Mod-1.7.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Gobyy'/212, l='Nouveau monde99988', x=-272.47, y=62.34, z=618.44]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D4
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.2.0 - Build 10.18.10.3643
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4
---------------------------------------------------------------------------
I tired removing all mods (excepted flans) and all content packs, still crashing.
It was working good months ago, i was able to play with this fleet pack but now i dont know why i am
getting this issue.

Please help me, i searched for hours and hours how to fix this but never found a good way.
Thanks.

**Comment by LilShrimp01** [comment]
I have the same exact problem. ;-;

**Comment by LilShrimp01** [comment]
You think it has to do something with Forge? I downloaded the latest Forge, so maybe I will downgrade and use the Recommended Forge. Imma try that and come back here if it works or not!

**Comment by Creepy11** [comment]
I'e found a way to make it work, after 2 hours of sesrch. Open Fleet Pack folder and remove all .DS_Store files, i did this and now its working fine, remove from vehicle folder, assets, ect.. all.

Tell me if it work 💃

**Comment by IsaacAbrahamson** [comment]
Could be a content pack problem. Make sure you have all the part packs especially mecha parts pack - this one can cause problems on vehicle placement if you don't have it.

**Comment by LilShrimp01** [comment]
I have all the simple parts and smp parts content packs. It still crashes me ;-;

**Comment by ChrisLane** [comment]
Seems this is likely a content pack problem. Are you able to replicate this issue in the latest Flan's mod version (5.1) and a official content pack?

**Comment by LilShrimp01** [comment]
Ok, it seems that all the JamioFlan packs work. I will now try each pack individually to see if they work and then find which one is causing the problem. I will not be able to try out the Manus packs being the SMP site is down.

**Comment by LilShrimp01** [comment]
Ok, so it seems every content pack worked EXCEPT the Fleet Pack. Lol, the one that Creeper was having trouble with before. I will be deleting the .DS_store to see if that works, but if it doesn't I will delete the pack all together.

**Comment by LilShrimp01** [comment]
Ok, so deleting the .DS_store folder did not fix the crash problem, so I will be deleting the Fleet PAck all together. Thanks for the help!
