### ISSUE TITLE
Flans mod Crashes When I Use It In a Mod Pack

### ISSUE THREAD

**Issue by Detrixukaon58** [FlansMods/FlansMod#820]
Hello,
for some reason Flans mod keeps on raising errors when i am using it in my mod pack...
Here's where the problem is apparently...
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:100)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:256)
	at noppes.animalbikes.AnimalBikes.registerBike(AnimalBikes.java:402)
	at noppes.animalbikes.AnimalBikes.load(AnimalBikes.java:281)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:491)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 190436696 bytes (181 MB) / 692060160 bytes (660 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 Optifine OptiFine_1.8_HD_U_F8 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHI	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UCHI	TooManyItems{1.8} [TooManyItems] (minecraft.jar) 
	UCHI	darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHI	battlegear2{1.8} [Mine & Blade Battlegear 2 - Bullseye] (1.8-MB_Battlegear2-Bullseye-1.0.10.1.jar) 
	UCHI	zeldaswordskills{1.8-3.2} [Zelda Sword Skills] (1.8-zeldaswordskills-3.2.jar) 
	UCHI	bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
	UCHI	Treecapitator{1.8} [Treecapitator] ([1.8]Treecapitator-universal-2.0.5.jar) 
	UCHI	advcapes{2.3} [Advanced Capes] (advancedcapes-2.3.jar) 
	UCHE	animalbikes{1.7.10} [Animal Bikes] (Animal-Bikes-Mod-1.8.jar) 
	UCHI	MovingWorld{MC1.8-V1.8.1} [Moving World] (movingworld-MC1.8-V1.8.1.jar) 
	UCHI	ArchimedesShipsPlus{MC1.8-V1.8} [Archimedes' Ships Plus] (archimedesshipsplus-MC1.8-V1.8.jar) 
	UCHI	wuppy29_slimedungeon{1.6.3} [Slime Dungeons] (Better Dungeons Mod 1.8.jar) 
	UCHI	chiselsandbits{1.6.2} [Chisels & Bits] (chiselsandbits-mc1.8-v1.6.2.jar) 
	UCHI	customnpcs{1.8.0} [CustomNPCs] (CustomNPCs_1.8.0.jar) 
	UCHI	DamageIndicatorsMod{3.3.2} [Damage Indicators] (Damage-Indicators-Mod-1.8.jar) 
	UCHI	frsm{1.5.69} [Fex's Random Stuff Mod] (FRSM-1.5.69.jar) 
	UCHI	fve{0.56} [Fex's Vehicle Extension] (FVE-0.56.jar) 
	UCHI	jum{1.0.2} [Jon's Useless Mod] (JonsUselessMod[v1.0.2][MC1.8].jar) 
	UCHI	lucky{6.0.1} [Lucky Block] (LuckyBlock_1-8_v6-0-1.zip) 
	UCHI	moSwords{v1} [Mo Swords Mod] (MoSwords-Mod-1.8.jar) 
	UCHI	cfm{3.6} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.6(1.8).jar) 
	UCHI	oceancraft{1.5.1} [Oceancraft] (oceancraft-1.5.2.jar) 
	UCHI	saoui{1.5a} [Sword Art Online UI] (saoui-1.8-1.5a.jar) 
	UCHI	mymod{1.1} [Swords++] (Swords++ v1.1 [1.8].jar) 
	UCHI	TooMuchTNT{3.0} [TooMuchTNT] (TooMuchTNT v3.0.jar) 
	Loaded coremods (and transformers): 
TMIForgeLoader (TooManyItems2015_02_14_1.8_Forge.jar)
  TMIForgeTransformer
Mine and Blade: Battlegear2 (1.8-MB_Battlegear2-Bullseye-1.0.10.1.jar)
  mods.battlegear2.coremod.transformers.EntityPlayerTransformer
  mods.battlegear2.coremod.transformers.ModelBipedTransformer
  mods.battlegear2.coremod.transformers.NetClientHandlerTransformer
  mods.battlegear2.coremod.transformers.NetServerHandlerTransformer
  mods.battlegear2.coremod.transformers.PlayerControllerMPTransformer
  mods.battlegear2.coremod.transformers.ItemRendererTransformer
  mods.battlegear2.coremod.transformers.RenderItemTransformer
  mods.battlegear2.coremod.transformers.MinecraftTransformer
  mods.battlegear2.coremod.transformers.ItemStackTransformer
  mods.battlegear2.coremod.transformers.ItemInWorldTransformer
  mods.battlegear2.coremod.transformers.EntityAIControlledByPlayerTransformer
  mods.battlegear2.coremod.transformers.EntityOtherPlayerMPTransformer
MovingWorldCoreMod (movingworld-MC1.8-V1.8.1.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4364' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 20.19.15.4364, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [PotterCraft 1.8.zip, Order of stone pack - HD]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

Please Help

Detrix.

**Comment by ChrisLane** [comment]
The issue comes from the Animal Bikes mod.
Third line of the stacktrace "at noppes.animalbikes.AnimalBikes.registerBike(AnimalBikes.java:402)"

Please report the crash to that mod author.

**Comment by Detrixukaon58** [comment]
But I don't have that mod in my pack.
