### ISSUE TITLE
Used Wrong Crash Report Refrence: Flans mod crashing.

### ISSUE THREAD

**Issue by Detrixukaon58** [FlansMods/FlansMod#821]
Sorry for This but this is the actual crash report.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  ItemPatchingLoader (ItemPhysic Lite 1.1.3 mc1.8.jar)
  CCCDeobfPlugin (unknown)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  LoadingPlugin (MinecraftCapes Forge1.8.jar)
  Mine and Blade: Battlegear2 (1.8-MB_Battlegear2-Bullseye-1.0.10.1.jar)
  MovingWorldCoreMod (movingworld-MC1.8-V1.8.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 21/07/16 19:52
Description: Initializing game

java.lang.IllegalArgumentException: ID is already registered: 31
	at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:100)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:256)
	at com.flansmod.common.FlansMod.init(FlansMod.java:269)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:491)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:100)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:256)
	at com.flansmod.common.FlansMod.init(FlansMod.java:269)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:491)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 291518336 bytes (278 MB) / 757477376 bytes (722 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 Optifine OptiFine_1.8_HD_U_F8 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHI	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UCHI	CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
	UCHI	MinecraftCapes{3.2} [MinecraftCapes] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
	UCHI	darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHI	itemphysic{1.1.2} [ItemPhysic] (minecraft.jar) 
	UCHI	battlegear2{1.8} [Mine & Blade Battlegear 2 - Bullseye] (1.8-MB_Battlegear2-Bullseye-1.0.10.1.jar) 
	UCHI	zeldaswordskills{1.8-3.2} [Zelda Sword Skills] (1.8-zeldaswordskills-3.2.jar) 
	UCHI	bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
	UCHI	Treecapitator{1.8} [Treecapitator] ([1.8]Treecapitator-universal-2.0.5.jar) 
	UCHI	MovingWorld{MC1.8-V1.8.1} [Moving World] (movingworld-MC1.8-V1.8.1.jar) 
	UCHI	ArchimedesShipsPlus{MC1.8-V1.8} [Archimedes' Ships Plus] (archimedesshipsplus-MC1.8-V1.8.jar) 
	UCHI	Backpack{2.0.1} [Backpack] (Backpacks-Mod-1.8.jar) 
	UCHI	wuppy29_slimedungeon{1.6.3} [Slime Dungeons] (Better Dungeons Mod 1.8.jar) 
	UCHI	XaeroBetterPvP{1.8.7} [Better PVP Mod] (BetterPvP_1.8.7_Forge_1.8.jar) 
	UCHI	speedytoolsmod{3.0.0} [Build Faster Mod] (BuildFaster-3-0-0-Minecraft-1-8.zip) 
	UCHI	chiselsandbits{1.6.2} [Chisels & Bits] (chiselsandbits-mc1.8-v1.6.2.jar) 
	UCHI	customnpcs{1.8.0} [CustomNPCs] (CustomNPCs_1.8.0.jar) 
	UCHI	MoCreatures{8.0.0.devA} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod-8.0.0.devA.jar) 
	UCHI	golems{2.09} [Extra Golems] (Extra-Golems[1.8]-2.09.jar) 
	UCHE	flansmod{5.1} [Flan's Mod] (Flan's Mod-1.8-5.1.jar) 
	UCHI	gvc{0.6.1} [§aGliby's§f Voice Chat Mod] (GlibysVC-1.8-0.6.1.jar) 
	UCHI	InfernalMobs{1.6.6} [Infernal Mobs] (InfernalMobs-1.8.jar) 
	UCHI	jum{1.0.2} [Jon's Useless Mod] (JonsUselessMod[v1.0.2][MC1.8].jar) 
	UCHI	lucky{6.0.1} [Lucky Block] (LuckyBlock_1-8_v6-0-1.zip) 
	UCHI	more{7.0 beta 2} [M-Ore mod] (M-Ore-Mod-1.8.jar) 
	UCHI	RadixCore{1.8-2.1.0} [RadixCore] (RadixCore-1.8-2.1.0-universal.jar) 
	UCHI	MCA{1.8-5.1.1.2} [Minecraft Comes Alive] (MCA-1.8-5.1.1.2-universal.jar) 
	UCHI	moredimensions{1.5} [MoreDimensions] (MoreDimensionsMod-1.5(1.8).jar) 
	UCHI	morematerials{1.0.20150301.0} [More Materials] (morematerials-1.0.20150615.0-MC1.8-20150614.jar) 
	UCHI	moSwords{v1} [Mo Swords Mod] (MoSwords-Mod-1.8.jar) 
	UCHI	cfm{3.6} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.6(1.8).jar) 
	UCHI	oceancraft{1.5.1} [Oceancraft] (oceancraft-1.5.2.jar) 
	UCHI	rpcraft{2.0} [RP Craft] (rpcraft-1.8-2.0.jar) 
	UCHI	saoui{1.5a} [Sword Art Online UI] (saoui-1.8-1.5a.jar) 
	UCHI	mymod{1.1} [Swords++] (Swords++ v1.1 [1.8].jar) 
	UCHI	TooMuchTNT{3.0} [TooMuchTNT] (TooMuchTNT v3.0.jar) 
	UCHI	VocaloidMod{0.0.1} [Vocaloid Mod] (VocaloidMod.0.0.2.-.1.8.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
ItemPatchingLoader (ItemPhysic Lite 1.1.3 mc1.8.jar)
  com.creativemd.itemphysic.ItemTransformer
CCCDeobfPlugin (unknown)
  
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
LoadingPlugin (MinecraftCapes Forge1.8.jar)
  MinecraftCapes.CBClassTransformer
Mine and Blade: Battlegear2 (1.8-MB_Battlegear2-Bullseye-1.0.10.1.jar)
  mods.battlegear2.coremod.transformers.EntityPlayerTransformer
  mods.battlegear2.coremod.transformers.ModelBipedTransformer
  mods.battlegear2.coremod.transformers.NetClientHandlerTransformer
  mods.battlegear2.coremod.transformers.NetServerHandlerTransformer
  mods.battlegear2.coremod.transformers.PlayerControllerMPTransformer
  mods.battlegear2.coremod.transformers.ItemRendererTransformer
  mods.battlegear2.coremod.transformers.RenderItemTransformer
  mods.battlegear2.coremod.transformers.MinecraftTransformer
  mods.battlegear2.coremod.transformers.ItemStackTransformer
  mods.battlegear2.coremod.transformers.ItemInWorldTransformer
  mods.battlegear2.coremod.transformers.EntityAIControlledByPlayerTransformer
  mods.battlegear2.coremod.transformers.EntityOtherPlayerMPTransformer
MovingWorldCoreMod (movingworld-MC1.8-V1.8.1.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.54' Renderer: 'GeForce 920M/PCIe/SSE2'
	Launched Version: 1.8-Forge11.14.4.1577
	LWJGL: 2.9.1
	OpenGL: GeForce 920M/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.54, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
(UPDATED FOR FULL CRASH REPORT)
Again i am sorry but i really nead this to work.

**Comment by ChrisLane** [comment]
Please update this ticket to contain the whole crash log.

**Comment by ChrisLane** [comment]
"java.lang.IllegalArgumentException: ID is already registered: 31"

That's the crucial bit I needed.
As far as I know, Flan's mod has automated entity IDs handled by forge and so I can only assume another mod is forcing an entity ID which is messing things up.

I recommend you go through removing other mods until it works to find the mod causing issues.
