### ISSUE TITLE
java.lang.NullPointException: Ticking entity error

### ISSUE THREAD

**Issue by gigiandearl** [FlansMods/FlansMod#823]
So I have been doing some experimenting with 1.8 flans mod and it seems whenever I try to shoot vehicles with a bazooka and when I kill them I get this error message:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 31/07/16 5:45 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.flansmod.common.driveables.DriveableType.getItemsRequired(DriveableType.java:523)
	at com.flansmod.common.driveables.EntityDriveable.killPart(EntityDriveable.java:1234)
	at com.flansmod.common.driveables.EntityDriveable.checkParts(EntityDriveable.java:1190)
	at com.flansmod.common.driveables.EntityDriveable.bulletHit(EntityDriveable.java:1150)
	at com.flansmod.common.guns.EntityBullet.func_70071_h_(EntityBullet.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.flansmod.common.driveables.DriveableType.getItemsRequired(DriveableType.java:523)
	at com.flansmod.common.driveables.EntityDriveable.killPart(EntityDriveable.java:1234)
	at com.flansmod.common.driveables.EntityDriveable.checkParts(EntityDriveable.java:1190)
	at com.flansmod.common.driveables.EntityDriveable.bulletHit(EntityDriveable.java:1150)
	at com.flansmod.common.guns.EntityBullet.func_70071_h_(EntityBullet.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Entity being ticked --
Details:
	Entity Type: flansmod.Bullet (com.flansmod.common.guns.EntityBullet)
	Entity ID: 4758
	Entity Name: entity.flansmod.Bullet.name
	Entity's Exact location: -30.94, 74.92, -153.63
	Entity's Block location: World: (-31,74,-154), Chunk: (at 1,4,6 in -2,-10; contains blocks -32,0,-160 to -17,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 4.15, -1.68, 2.16
Stacktrace:
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['TheEmmaDilemma'/4566, l='New World', x=-30.94, y=73.30, z=-153.63]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 1043251288871852051
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-36,64,-140), Chunk: (at 12,4,4 in -3,-9; contains blocks -48,0,-144 to -33,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2942 game time, 2942 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 36383 (now: false), thunder time: 12827 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.2.0-42-generic
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 211813920 bytes (202 MB) / 572968960 bytes (546 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D4 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{1.0.4.94} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.94-universal.jar) 
	UCHIJAAAAAAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAAAAAAA	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) 
	UCHIJAAAAAAAAA	flansmod{4.10.0} [Flan's Mod] (Flan's Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAAAAAAA	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) 
	UCHIJAAAAAAAAA	MapWriter{2.1.5} [MapWriter] (MapWriter-1.7.10-2.1.6.jar) 
	UCHIJAAAAAAAAA	Sampler{1.60} [Sampler] (sampler-1.60.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['TheEmmaDilemma'/4566, l='New World', x=-30.94, y=73.30, z=-153.63]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D4
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 2.1 Mesa 11.0.2
	OpenGlRenderer: Mesa DRI Intel(R) Ironlake Mobile 
	OpenGlVendor: Intel Open Source Technology Center
	CpuCount: 4

Its extreamly annoying and it only happens with the new/redone models added in 1.8 flans mod. I really just want help or a guide to help solve this problem, as I do sort of know java and I want a fix bad, as I have tried a lot of stuff, like compiling them into a .class via SMP toolbox and gradle

**Comment by gigiandearl** [comment]
I figured out what caused it, I forgot to add the new simple parts pack, silly me
