### ISSUE TITLE
Server crash when entering a vehicle while holding mouse clicked

### ISSUE THREAD

**Issue by blooditor** [FlansMods/FlansMod#852]
Hey,
the server/integrated server crashes on MC 1.8 5.3.1 when a player enters a vehicle and holding the right mouse button at the same time (so if you want to enter a vehicle and hold the mouse button a bit too long). The singleplayer freezes and the multiplayer server times out.
I couldn't find the exact cause of the problem, only that the vehicle want's to shoot something because the mouse button is clicked and something goes wrong (Error and not Exception somehow).

Because of the freeze there is no crash recognized most of the time. There is one I could find:

`java.lang.Error
	at com.flansmod.common.vector.Matrix4f.rotate(Matrix4f.java:520)
	at com.flansmod.common.vector.Matrix4f.rotate(Matrix4f.java:509)
	at com.flansmod.common.RotatedAxes.findLocalVectorGlobally(RotatedAxes.java:186)
	at com.flansmod.common.driveables.EntityDriveable.rotate(EntityDriveable.java:1112)
	at com.flansmod.common.driveables.EntityDriveable.getOrigin(EntityDriveable.java:733)
	at com.flansmod.common.driveables.EntityDriveable.shootEach(EntityDriveable.java:535)
	at com.flansmod.common.driveables.EntityDriveable.shoot(EntityDriveable.java:516)
	at com.flansmod.common.driveables.EntityDriveable.onUpdate(EntityDriveable.java:950)
	at com.flansmod.common.driveables.EntityPlane.onUpdate(EntityPlane.java:316)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2031)
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:758)
	at net.minecraft.world.World.updateEntity(World.java:1997)
	at net.minecraft.world.World.updateEntities(World.java:1823)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:587)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:775)
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:385)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540)
	at java.lang.Thread.run(Unknown Source)`

I was able to bypass the error by adding one thing in onUpdate() line 916 of EntityVehicle:
if(rightMouseHeld && getDriveableType().modeSecondary == EnumFireMode.FULLAUTO)
				
//added bypass so it can't call the shoot if the vehicle is not running, needs something better here:
				
if(throttle > 0)
       shoot(true);

**Comment by theCVDH** [comment]
Have the same issue also with your litte bypass
java.lang.Error is realy unspezific .(

**Comment by blooditor** [comment]
Its really weird, also happens in some other cases I couldn't reproduce yet

**Comment by blooditor** [comment]
**Looks like I found the issue.** 
It's in EntityDriveable#shoot()
The loop `while(getShootDelay(secondary) <= 0.0f)`
causes an infinite loop and crashes the game.
Looks like you can simply fix that by replacing while(...) with if(...)

**Comment by gmax9803** [comment]
Will anyone fix this?

**Comment by ChrisLane** [comment]
Couldn't reproduce in latest version

**Comment by gmax9803** [comment]
*|MC:SUBJECT|*    

 		  [1] 

	Dear Chris Lane, 

	maxg@kmail.org is only allowed to receive email from approved
senders. This means that your email to maxg@kmail.org will be delayed
until the parent of this child reviews and approves the message. There
is no guarantee that your message will be delivered to its intended
recipient. SUBJECT: Re: [FlansMods/FlansMod] Server crash when
entering a vehicle while holding mouse clicked (#852)
 STATUS: Delayed / In Parent's Mail Queue

	This approval process is due to a safety setting being set by this
child's parent. The parent is using KidsEmail.org to protect his/her
family. 

	Protect your family with KidsEmail.org! 

 		  [2] 

 		  [3] 

 		  [4] 

 		  [5] 

 		  [6] 

This message was intended for
reply@reply.github.com.
If you do not wish to receive _ANY_ emails from KidsEmail.org in the
future, please follow the link below to unsubscribe.
http://www.kidsemail.org/unsubscribe.php?SM_USER=reply@reply.github.com&DE_USER=d1043578942177c1895402baee26b4b8375a5b4b

Links:
------
[1] https://www.kidsemail.org
[2] https://twitter.com/KidsEmail
[3] https://www.instagram.com/kidsemail/
[4] https://www.facebook.com/KidsEmail.org
[5] https://www.pinterest.com/kidsemail1/
[6] https://www.kidsemail.org

**Comment by gmax9803** [comment]
*|MC:SUBJECT|*    

 		  [1] 

	Dear Chris Lane, 

	maxg@kmail.org is only allowed to receive email from approved
senders. This means that your email to maxg@kmail.org will be delayed
until the parent of this child reviews and approves the message. There
is no guarantee that your message will be delivered to its intended
recipient. SUBJECT: Re: [FlansMods/FlansMod] Server crash when
entering a vehicle while holding mouse clicked (#852)
 STATUS: Delayed / In Parent's Mail Queue

	This approval process is due to a safety setting being set by this
child's parent. The parent is using KidsEmail.org to protect his/her
family. 

	Protect your family with KidsEmail.org! 

 		  [2] 

 		  [3] 

 		  [4] 

 		  [5] 

 		  [6] 

This message was intended for
reply@reply.github.com.
If you do not wish to receive _ANY_ emails from KidsEmail.org in the
future, please follow the link below to unsubscribe.
http://www.kidsemail.org/unsubscribe.php?SM_USER=reply@reply.github.com&DE_USER=e5f33342ceb87502bb95a95443ed201bd9d31b00

Links:
------
[1] https://www.kidsemail.org
[2] https://twitter.com/KidsEmail
[3] https://www.instagram.com/kidsemail/
[4] https://www.facebook.com/KidsEmail.org
[5] https://www.pinterest.com/kidsemail1/
[6] https://www.kidsemail.org
