### ISSUE TITLE
Flans mod crash when spawning vehicles

### ISSUE THREAD

**Issue by AgentD1** [FlansMods/FlansMod#867]
An Entity type com.flansmod.common.driveables.EntityPlane has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_70109_d(Entity.java:1359)
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1298)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:346)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197)
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256)
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318)
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:350)
	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:241)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:480)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NullPointerException
	at com.flansmod.common.driveables.DriveableData.writeToNBT(DriveableData.java:82)
	at com.flansmod.common.driveables.EntityDriveable.func_70014_b(EntityDriveable.java:157)
	at com.flansmod.common.driveables.EntityPlane.func_70014_b(EntityPlane.java:73)
	at net.minecraft.entity.Entity.func_70109_d(Entity.java:1342)
	... 11 more

**Comment by xFaiafokkusu** [comment]
You have the same issue what I have

**Comment by Fexcraft** [comment]
Is the plane from an Official pack or no?

**Comment by AgentD1** [comment]
It was a vehicle from the Modern Weapons content pack.
