### ISSUE TITLE
1.8 game crash when i place vehicles

### ISSUE THREAD

**Issue by KRYHUNPL** [FlansMods/FlansMod#868]
when i install flans mod i try to spawn buggy, game crashed
when i install ww2 pack i try to spawn some tanks, game crashed

**Comment by KRYHUNPL** [comment]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:381)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)

-- Entity being ticked --
Details:
	Entity Type: Vehicle (com.flansmod.common.driveables.EntityVehicle)
	Entity ID: 6285
	Entity Name: M24 Chaffee
	Entity's Exact location: -883,50, 71,50, 461,50
	Entity's Block location: -884,00,71,00,461,00 - World: (-884,71,461), Chunk: (at 12,4,13 in -56,28; contains blocks -896,0,448 to -881,255,463), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['KRYHUN'/263, l='New World', x=-885,98, y=70,00, z=463,92]]
	Chunk stats: ServerChunkCache: 819 Drop: 0
	Level seed: -7567177195400478896
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: -901,00,64,00,498,00 - World: (-901,64,498), Chunk: (at 11,4,2 in -57,31; contains blocks -912,0,496 to -897,255,511), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 641 game time, 641 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 60403 (now: false), thunder time: 78628 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 289714872 bytes (276 MB) / 835391488 bytes (796 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar) 
	UCHIJAAAA	Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.5.34} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	lootablebodies{1.3.6} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.3.6.jar) 
	UCHIJAAAA	flansmod{5.0} [Flan's Mod] (Flan's Mod-1.8-5.0.jar) 
	UCHIJAAAA	flansmodapocalypse{1.0} [Flan's Mod: Apocalypse] (Flan's Mod Apocalypse-1.8-1.0.jar) 
	UCHIJAAAA	inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
CCCDeobfPlugin (unknown)
  
CodeChickenCorePlugin (CodeChickenCore-1.8.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['KRYHUN'/263, l='New World', x=-885,98, y=70,00, z=463,92]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[23:11:08] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:571]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\krystek\AppData\Roaming\.minecraft\crash-reports\crash-2017-08-31_23.11.08-server.txt
[23:11:08] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[23:11:08] [Server thread/INFO]: Saving worlds
[23:11:08] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[23:11:08] [Server thread/ERROR] [FML]: An Entity type com.flansmod.common.driveables.EntityVehicle has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_70109_d(Entity.java:1420) ~[wv.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1349) ~[wv.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:357) [bfy.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:183) [bfy.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:246) [qs.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:305) [qs.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:938) [qt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:363) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:395) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:328) [cyk.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:531) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.flansmod.common.driveables.DriveableData.writeToNBT(DriveableData.java:84) ~[DriveableData.class:?]
	at com.flansmod.common.driveables.EntityDriveable.func_70014_b(EntityDriveable.java:163) ~[EntityDriveable.class:?]
	at com.flansmod.common.driveables.EntityVehicle.func_70014_b(EntityVehicle.java:84) ~[EntityVehicle.class:?]
	at net.minecraft.entity.Entity.func_70109_d(Entity.java:1403) ~[wv.class:?]
	... 11 more
[23:11:08] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[23:11:08] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[23:11:08] [Server thread/INFO]: Saving chunks for level 'New World'/Apocalypse
[23:11:09] [Server thread/INFO] [FML]: Unloading dimension 0
[23:11:09] [Server thread/INFO] [FML]: Unloading dimension -1
[23:11:09] [Server thread/INFO] [FML]: Unloading dimension 1
[23:11:09] [Server thread/INFO] [FML]: Unloading dimension 2
[23:11:09] [Server thread/INFO] [FML]: Applying holder lookups
[23:11:09] [Server thread/INFO] [FML]: Holder lookups applied
[23:11:09] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[23:11:09] [Client thread/INFO] [FML]: Server terminated.

**Comment by xFaiafokkusu** [comment]
I think you have to disabled server...
