### ISSUE TITLE
Opening fuel menu crashes client and server when a fuel can is used up

### ISSUE THREAD

**Issue by TehWakko** [FlansMods/FlansMod#917]
I'm playing on my friends server and when I try to view the fuel menu in a vehicle after one of my cans has been used (or as it's being used up) it will crash my game, and also the server (My friend owns the server, but it is a third party service). Whenever I cause the issue I am the only one who crashes, my friends just disconnect from the server. This is on the Flan's WWII pack.

Flan's Mod 5.5.2 with simple parts, ww2 content pack, and ye olde content pack
on Minecraft Forge 14.23.4.2703

If there's anything else that you could use to help resolve this, I'll provide it. Thank you for your time.

_Edit: Something similar happens in singleplayer as well. The game freezes (It doesn't say "Not Responding" though) and makes it unplayable._

_I should also mention that I'm using MCUpdater to launch the custom modpack. In the config I got this when my singleplayer game froze:_
[05:13:33] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:438) ~[aip.class:?]
	at net.minecraft.inventory.Container.func_75142_b(Container.java:82) ~[afr.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324) ~[oq.class:?]
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2013) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2480) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70098_U(EntityPlayer.java:461) ~[aed.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1985) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2050) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2050) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1756) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more

**Comment by ChrisLane** [comment]
Hi, could you please check if the bug still happens with the files included in the zip below?
Please note that this is a test version only and should not be used on any worlds that you have not backed up.

[flans-test-15-10.zip](https://github.com/FlansMods/FlansMod/files/2480558/flans-test-15-10.zip)

**Comment by Jedude1** [comment]
tried to crash a few times in a few ways, seems fixed!

**Comment by ChrisLane** [comment]
Great! Thanks for testing.

**Comment by sambam05** [comment]
Hi i am having the same problem

**Comment by sambam05** [comment]
This is with the Latest update

**Comment by Liruxo** [comment]
Please open a new bug report. Instruction on how to do so can be found here:
https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting

Edit: Already existing, refer to #1228 for further information
