### ISSUE TITLE
Crash with empty fuel tank

### ISSUE THREAD

**Issue by Smiertzlen** [FlansMods/FlansMod#934]
I have discovered a crash as soon as I empty an entire fuel tank into a planes internal tank.

[20:09:31] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:438) ~[aip.class:?]
	at net.minecraft.inventory.Container.func_75142_b(Container.java:82) ~[afr.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324) ~[oq.class:?]
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2013) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2480) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70098_U(EntityPlayer.java:461) ~[aed.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1985) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2050) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2050) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1756) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more

I tried it with different planes, on which the same error occured. Could it be, that, as soon as the fuel left in the can reaches 0, that NULL is returned to the item slot instead of an ItemStack.empty?
That would explain this weird behaviour.

I am currently using Flan 1.12.2-5.5.2 with SimpleParts, ModernWarfare and WW" content packs

**Comment by ChrisLane** [comment]
Hi, could you please check if the bug still happens with the files included in the zip below?
Please note that this is a test version only and should not be used on any worlds that you have not backed up.

[flans-test-15-10.zip](https://github.com/FlansMods/FlansMod/files/2480558/flans-test-15-10.zip)
