### ISSUE TITLE
Explosive Kills Crash the Server

### ISSUE THREAD

**Issue by korlandril** [FlansMods/FlansMod#965]
Currently testing a custom modpack with version 5.6 Beta of Flan's Mod installed. An explosion with the Barrett .50 Cal explosive ammo shot at a mob crashes the whole server with this output

```
[12:08:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingAttackEvent@42985d0d:
java.lang.NullPointerException: null
	at net.minecraft.util.EntityDamageSource.func_188404_v(SourceFile:60) ~[us.class:?]
	at thebetweenlands.common.entity.rowboat.EntityWeedwoodRowboat.onLivingAttacked(EntityWeedwoodRowboat.java:1027) ~[EntityWeedwoodRowboat.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_819_EntityWeedwoodRowboat_onLivingAttacked_LivingAttackEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:572) [ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.hookModAttack(EntityLivingBase.java:5814) [vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3482) [vp.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70) [ade.class:?]
	at com.flansmod.common.FlansModExplosion.func_77278_a(FlansModExplosion.java:175) [FlansModExplosion.class:?]
	at com.flansmod.common.FlansModExplosion.<init>(FlansModExplosion.java:75) [FlansModExplosion.class:?]
	at com.flansmod.common.guns.EntityBullet.OnDetonate(EntityBullet.java:599) [EntityBullet.class:?]
	at com.flansmod.common.guns.ItemGun.DoInstantShot(ItemGun.java:701) [ItemGun.class:?]
	at com.flansmod.common.guns.ItemGun.ServerHandleShotData(ItemGun.java:678) [ItemGun.class:?]
	at com.flansmod.common.network.PacketShotData.handleServerSide(PacketShotData.java:152) [PacketShotData.class:?]
	at com.flansmod.common.network.PacketHandler.handleServerPackets(PacketHandler.java:174) [PacketHandler.class:?]
	at com.flansmod.common.CommonTickHandler.tick(CommonTickHandler.java:41) [CommonTickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_CommonTickHandler_tick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[12:08:16] [Server thread/ERROR] [FML]: Index: 19 Listeners:
[12:08:16] [Server thread/ERROR] [FML]: 0: NORMAL
[12:08:16] [Server thread/ERROR] [FML]: 1: ASM: com.flansmod.common.PlayerHandler@6c8aecbe onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 2: ASM: com.flansmod.common.teams.TeamsManagerRanked@5d2924f onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 3: ASM: class twilightforest.item.ItemTFKnightlySword onDamage(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 4: ASM: class twilightforest.item.ItemTFMinotaurAxe onAttack(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 5: ASM: class twilightforest.TFEventListener livingAttack(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 6: ASM: class com.afg.regeneration.superpower.TimelordHandler onAttacked(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 7: ASM: com.shinoow.abyssalcraft.common.handlers.AbyssalCraftEventHooks@68cc933 damageStuff(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 8: ASM: lucraft.mods.lucraftcore.superpowers.capabilities.CapabilitySuperpower$CapabilitySuperpowerEventHandler@69e04ac2 onLivingAttackEvent(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 9: ASM: lucraft.mods.lucraftcore.karma.KarmaEventHandler@6c037c37 onLivingAttackEvent(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 10: ASM: lucraft.mods.lucraftcore.advancedcombat.AdvancedCombatEventHandler@61e11227 onAttacked(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 11: ASM: com.lycanitesmobs.PotionEffects@180633ab onLivingAttack(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 12: ASM: ItemGasMask{Name=null} onEntityAttacked(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 13: ASM: ItemFreeRunners{Name=null} onEntityAttacked(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 14: ASM: teamroots.roots.EventManager@5184c7cb onLivingAttack(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 15: ASM: teamroots.roots.effect.EffectFireResist@2e497dd1 onLivingAttack(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 16: ASM: dynamicswordskills.DSSCombatEvents@3e0ec693 onAttacked(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 17: ASM: erebus.core.handler.PlayerInWallDamageHandler@155a5ecc onEntityMounted(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 18: ASM: INSTANCE onLivingAttacked(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 19: ASM: class thebetweenlands.common.entity.rowboat.EntityWeedwoodRowboat onLivingAttacked(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 20: ASM: BattleSign{Name=tconstruct.battlesign} reflectProjectiles(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 21: LOW
[12:08:16] [Server thread/ERROR] [FML]: 22: ASM: class thebetweenlands.common.handler.AttackDamageHandler onEntityAttack(Lnet/minecraftforge/event/entity/living/LivingAttackEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@15a4274d:
java.lang.NullPointerException: null
	at net.minecraft.util.EntityDamageSource.func_188404_v(SourceFile:60) ~[us.class:?]
	at thebetweenlands.common.entity.rowboat.EntityWeedwoodRowboat.onLivingAttacked(EntityWeedwoodRowboat.java:1027) ~[EntityWeedwoodRowboat.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_819_EntityWeedwoodRowboat_onLivingAttacked_LivingAttackEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:572) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.hookModAttack(EntityLivingBase.java:5814) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3482) ~[vp.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70) ~[ade.class:?]
	at com.flansmod.common.FlansModExplosion.func_77278_a(FlansModExplosion.java:175) ~[FlansModExplosion.class:?]
	at com.flansmod.common.FlansModExplosion.<init>(FlansModExplosion.java:75) ~[FlansModExplosion.class:?]
	at com.flansmod.common.guns.EntityBullet.OnDetonate(EntityBullet.java:599) ~[EntityBullet.class:?]
	at com.flansmod.common.guns.ItemGun.DoInstantShot(ItemGun.java:701) ~[ItemGun.class:?]
	at com.flansmod.common.guns.ItemGun.ServerHandleShotData(ItemGun.java:678) ~[ItemGun.class:?]
	at com.flansmod.common.network.PacketShotData.handleServerSide(PacketShotData.java:152) ~[PacketShotData.class:?]
	at com.flansmod.common.network.PacketHandler.handleServerPackets(PacketHandler.java:174) ~[PacketHandler.class:?]
	at com.flansmod.common.CommonTickHandler.tick(CommonTickHandler.java:41) ~[CommonTickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_CommonTickHandler_tick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[12:08:16] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[12:08:16] [Server thread/ERROR] [FML]: 0: NORMAL
[12:08:16] [Server thread/ERROR] [FML]: 1: ASM: com.flansmod.common.CommonTickHandler@76f85dd5 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 2: ASM: class com.zarak.zaraklib.Events tickTimer(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 3: ASM: net.minecraftforge.common.ForgeInternalHandler@39dd5abd onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 4: ASM: spongeforge onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 5: ASM: codechicken.enderstorage.network.TankSynchroniser@5759d5d4 tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 6: ASM: class erebus.core.capabilities.base.EntityCapabilityHandler onServerTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 7: ASM: lucraft.mods.lucraftcore.advancedcombat.AdvancedCombatEventHandler@61e11227 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 8: ASM: mcjty.meecreeps.ForgeEventHandlers@6faff9e4 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 9: ASM: INSTANCE onServerTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 10: ASM: weather2.EventHandlerFML@39f909a9 tickServer(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 11: ASM: com.pg85.otg.forge.events.ServerEventListener@27377ad4 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 12: ASM: CoroUtil.forge.EventHandlerFML@56994bed tickServer(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 13: ASM: erebus.world.teleporter.TeleporterHandler@2a1c018a onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 14: ASM: erebus.world.SpawnerErebus@8502b5 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 15: ASM: Network Registry:
[] onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 16: ASM: org.millenaire.common.forge.ServerTickHandler@2f222532 tickStart(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 17: ASM: ZombieAwareness.ZAEventHandler@4c351d1 tickServer(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 18: ASM: class thebetweenlands.common.handler.WorldEventHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 19: ASM: class thebetweenlands.common.capability.base.EntityCapabilityHandler onServerTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 20: ASM: thebetweenlands.common.world.biome.spawning.MobSpawnHandler@5b05dc64 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 21: ASM: class thebetweenlands.common.handler.EnvironmentEventOverridesHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 22: ASM: org.blockartistry.DynSurround.server.services.ServiceManager@73eeada0 tickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 23: ASM: ivorius.reccomplex.events.handlers.RCForgeEventHandler@43e9bae8 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[12:08:16] [Server thread/ERROR] [FML]: 24: LOWEST
[12:08:16] [Server thread/ERROR] [FML]: 25: ASM: class codechicken.lib.internal.CCLLog onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[12:08:16] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.util.EntityDamageSource.func_188404_v(SourceFile:60) ~[us.class:?]
	at thebetweenlands.common.entity.rowboat.EntityWeedwoodRowboat.onLivingAttacked(EntityWeedwoodRowboat.java:1027) ~[EntityWeedwoodRowboat.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_819_EntityWeedwoodRowboat_onLivingAttacked_LivingAttackEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:572) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.hookModAttack(EntityLivingBase.java:5814) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3482) ~[vp.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70) ~[ade.class:?]
	at com.flansmod.common.FlansModExplosion.func_77278_a(FlansModExplosion.java:175) ~[FlansModExplosion.class:?]
	at com.flansmod.common.FlansModExplosion.<init>(FlansModExplosion.java:75) ~[FlansModExplosion.class:?]
	at com.flansmod.common.guns.EntityBullet.OnDetonate(EntityBullet.java:599) ~[EntityBullet.class:?]
	at com.flansmod.common.guns.ItemGun.DoInstantShot(ItemGun.java:701) ~[ItemGun.class:?]
	at com.flansmod.common.guns.ItemGun.ServerHandleShotData(ItemGun.java:678) ~[ItemGun.class:?]
	at com.flansmod.common.network.PacketShotData.handleServerSide(PacketShotData.java:152) ~[PacketShotData.class:?]
	at com.flansmod.common.network.PacketHandler.handleServerPackets(PacketHandler.java:174) ~[PacketHandler.class:?]
	at com.flansmod.common.CommonTickHandler.tick(CommonTickHandler.java:41) ~[CommonTickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_CommonTickHandler_tick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[12:08:16] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: J:\ForgeServer\.\crash-reports\crash-2018-10-30_12.08.16-server.txt
[12:08:16] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[12:08:16] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[12:08:16] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[12:08:16] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -1
[12:08:16] [Server thread/INFO] [Sponge]: Unloading world [DIM-1] (DIM-1)
[12:08:16] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 1
[12:08:16] [Server thread/INFO] [Sponge]: Unloading world [DIM1] (DIM1)
[12:08:16] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 7
[12:08:16] [Server thread/INFO] [Sponge]: Unloading world [DIM7] (DIM7)
[12:08:16] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 20
[12:08:16] [Server thread/INFO] [Sponge]: Unloading world [DIM20] (DIM20)
[12:08:16] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 50
[12:08:18] [Server thread/INFO] [Sponge]: Unloading world [Abyssal_Wasteland] (DIM50)
[12:08:18] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 51
[12:08:18] [Server thread/INFO] [Sponge]: Unloading world [The_Dreadlands] (DIM51)
[12:08:18] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 52
[12:08:18] [Server thread/INFO] [Sponge]: Unloading world [Omothol] (DIM52)
[12:08:18] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 53
[12:08:18] [Server thread/INFO] [Sponge]: Unloading world [The_Dark_Realm] (DIM53)
[12:08:18] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 66
[12:08:18] [Server thread/INFO] [Sponge]: Unloading world [DIM66] (DIM66)
[12:08:18] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up all world data: 1 data blobs
[12:08:18] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[12:08:18] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[12:08:18] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
```

**Comment by ChrisLane** [comment]
"`thebetweenlands.common.entity.rowboat.EntityWeedwoodRowboat.onLivingAttacked(EntityWeedwoodRowboat.java:1027) ~[EntityWeedwoodRowboat.class:?]`"

Looks like a bug in "The Betweenlands"

Could you confirm that the crash does not occur when the other mod has been removed?

**Comment by korlandril** [comment]
> "`thebetweenlands.common.entity.rowboat.EntityWeedwoodRowboat.onLivingAttacked(EntityWeedwoodRowboat.java:1027) ~[EntityWeedwoodRowboat.class:?]`"
> 
> Looks like a bug in "The Betweenlands"
> 
> Could you confirm that the crash does not occur when the other mod has been removed?

Confirmed. Removing The Betweenlands mod lets me shoot mobs again without crashing.

**Comment by TheCyberBrick** [comment]
I don't think this is a mistake on our side because there's no way of knowing whether we can call EntityDamageSource#getDamageLocation() or not. EntityDamageSource#getDamageLocation() shouldn't just crash like that.  
Pretty sure the `@Nullable` on EntityDamageSource#damageSourceEntity is a mistake because if it is null it'll cause a NPE in EntityDamageSource#getDamageLocation(). Haven't actually found any vanilla use case where EntityDamageSource#damageSourceEntity is null either.  
Since your custom damage sources' EntityDamageSource#damageSourceEntity can be null, changing your custom damage sources to return null in getDamageLocation() if EntityDamageSource#damageSourceEntity is null would solve this crash.

**Comment by korlandril** [comment]
Here's a pastebin of my clientside modlist just in case:
https://pastebin.com/aXfe5qVb

**Comment by ChrisLane** [comment]
> I don't think this is a mistake on our side because there's no way of knowing whether we can call EntityDamageSource#getDamageLocation() or not. EntityDamageSource#getDamageLocation() shouldn't just crash like that.
> Pretty sure the `@Nullable` on EntityDamageSource#damageSourceEntity is a mistake because if it is null it'll cause a NPE in EntityDamageSource#getDamageLocation(). Haven't actually found any vanilla use case where EntityDamageSource#damageSourceEntity is null either.
> Since your custom damage sources' EntityDamageSource#damageSourceEntity can be null, changing your custom damage sources to return null in getDamageLocation() if EntityDamageSource#damageSourceEntity is null would solve this crash.

I've taken a look and agree that the `@Nullable` annotations do seem incorrect.
I'm not willing to do error checking for the Minecraft/Forge code within Flan's Mod and so will instead create a damageSourceEntity to pass to avoid NPEs.

@korlandril Could you try the version contained in the zip below with The Betweenlands and check whether the issue is fixed?
[test-issue965-1.zip](https://github.com/FlansMods/FlansMod/files/2532221/test-issue965-1.zip)

**Comment by korlandril** [comment]
The file you provided seems to have fixed the issue both in singleplayer and multiplayer with no outstanding error or warning messages. Thank you!
