### ISSUE TITLE
minercaft crashes after loading with any content pack installed

### ISSUE THREAD

**Issue by gnomed-by-steve** [FlansMods/FlansMod#978]
**To Reproduce**
Steps to reproduce the crash:
1. Get any mod that uses content packs (MTS, flan, etc.)
2. run minecraft
3. minercaft dies

**Screenshots**
Nope, can't.

**Versions (please complete the following information):**
 - Forge: 1.12.2-forge1.12.2-14.23.5.2796
 - Flan's Mod: latest 5.5.2

**Additional context**

crash report details:

	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:529)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:235)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I've come to the conclusion that this isnt a problem with any other mods I have, as isolating the mod didn't do any good.

I will attempt doing multiple more things (i.e. running flan/mts with no content packs installed and using other forge versions) to see if there is a temporary fix for the problem.

**Comment by ChrisLane** [comment]
@gnomed-by-steve Can you please provide the full crash log?

**Comment by gnomed-by-steve** [comment]
> 
> 
> @gnomed-by-steve Can you please provide the full crash log?

Sure:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-87.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  SmoothWaterCore (SmoothWater-0.1.4.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.1-core.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 12/15/18 5:50 PM
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:529)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:235)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:529)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:235)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 495448496 bytes (472 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 Optifine OptiFine_1.12.2_HD_U_E3 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                        | Signature                                |
	|:------ |:-------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2796.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2796      | forge-1.12.2-14.23.5.2796.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | foamfixcore          | 7.7.4             | minecraft.jar                                 | None                                     |
	| LCHIJA | aether_legacy        | 1.12.2-v3.2       | aether_legacy-1.12.2-v3.2.jar                 | None                                     |
	| LCHIJA | appliedenergistics2  | rv6-stable-4      | appliedenergistics2-rv6-stable-4.jar          | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | baubles              | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | biomesoplenty        | 7.0.1.2419        | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar | None                                     |
	| LCHIJA | chameleon            | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                     | None                                     |
	| LCHIJA | familiarfauna        | 1.0.11            | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
	| LCHIJA | flansmod             | 5.5.2             | Flan's Mod-1.12.2-5.5.2.jar                   | None                                     |
	| LCHIJA | flansmodapocalypse   | 1.0               | Flan's Mod-1.12.2-5.5.2.jar                   | None                                     |
	| LCHIJA | foamfix              | 0.10.3-1.12.2     | foamfix-0.10.3-1.12.2.jar                     | None                                     |
	| LCHIJA | cfm                  | 6.2.0             | furniture-6.2.0-1.12.2.jar                    | None                                     |
	| LCHIJA | jei                  | 4.13.1.225        | jei_1.12.2-4.13.1.225.jar                     | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.5.3      | journeymap-1.12.2-5.5.3.jar                   | None                                     |
	| LCHIJA | lex                  | 1.0.8             | LibEx-1.12.2-1.0.8.jar                        | None                                     |
	| LCHIJA | lostcities           | 2.0.12            | lostcities-1.12-2.0.12.jar                    | None                                     |
	| LCHIJA | malisiscore          | 1.12.2-6.4.0      | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| LCHIJA | malisisdoors         | 1.12.2-7.3.0      | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LCHIJA | mantle               | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar                      | None                                     |
	| LCHIJA | nex                  | 2.0.8             | NetherEx-1.12.2-2.0.8.jar                     | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2z           | Pam's+HarvestCraft+1.12.2za.jar               | None                                     |
	| LCHIJA | realdrops            | 1.2.14            | RealisticItemDrops-1.2.14.jar                 | None                                     |
	| LCHIJA | toughasnails         | 3.1.0.139         | ToughAsNails-1.12.2-3.1.0.139-universal.jar   | None                                     |
	| LCHIJA | slurp                | 0.3               | slurp-1.12-0.3.jar                            | None                                     |
	| LCHIJA | smoothwater          | 0.1.4             | SmoothWater-0.1.4.jar                         | None                                     |
	| LCHIJA | storagedrawers       | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.8.jar               | None                                     |
	| LCHIJA | supertnt             | 1.0.1             | SuperTNT-1.12.2-1.0.1.jar                     | None                                     |
	| LCHIJA | tconstruct           | 1.12.2-2.11.0.106 | TConstruct-1.12.2-2.11.0.106.jar              | None                                     |
	| LCHIJA | thaumcraft           | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHIJA | immersiveengineering | 0.12-87           | ImmersiveEngineering-0.12-87.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | thebetweenlands      | 3.4.1             | TheBetweenlands-3.4.1-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-87.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
SmoothWaterCore (SmoothWater-0.1.4.jar)
  pl.asie.smoothwater.SmoothWaterTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.1-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13542 Compatibility Profile Context 25.20.14011.9004' Renderer: 'AMD Radeon R9 200 Series'
	AE2 Version: stable rv6-stable-4 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2796
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 200 Series GL version 4.5.13542 Compatibility Profile Context 25.20.14011.9004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13542 Compatibility Profile Context 25.20.14011.9004
	OpenGlRenderer: AMD Radeon R9 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by ChrisLane** [comment]
@gnomed-by-steve From the crash log: "One of more entry values did not copy to the correct id. Check log for details!"

Could you please post a link to a paste of the normal log file? Recommend https://gist.github.com/

**Comment by gnomed-by-steve** [comment]
Log was fairly small so here you go:


[19:42:00] [Client thread/INFO]: Setting user: (censor)
[19:42:02] [Client thread/WARN]: Skipping bad option: lastServer:
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.pickItem:key.mouse.middle
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.playerlist:key.keyboard.tab
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.advancements:key.keyboard.l
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.hotbar.5:key.keyboard.5
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.hotbar.6:key.keyboard.6
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.hotbar.7:key.keyboard.7
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.hotbar.8:key.keyboard.8
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.hotbar.1:key.keyboard.1
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.hotbar.2:key.keyboard.2
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.hotbar.3:key.keyboard.3
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.hotbar.4:key.keyboard.4
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.sprint:key.keyboard.left.control
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.forward:key.keyboard.w
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.drop:key.keyboard.q
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.back:key.keyboard.s
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.attack:key.mouse.left
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.use:key.mouse.right
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.saveToolbarActivator:key.keyboard.unknown
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.smoothCamera:key.keyboard.unknown
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.right:key.keyboard.d
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.jump:key.keyboard.space
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.sneak:key.keyboard.left.shift
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.spectatorOutlines:key.keyboard.unknown
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.left:key.keyboard.a
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.command:key.keyboard.slash
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.screenshot:key.keyboard.f2
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.hotbar.9:key.keyboard.9
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.togglePerspective:key.keyboard.f5
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.chat:key.keyboard.t
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.inventory:key.keyboard.e
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.fullscreen:key.keyboard.f11
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.loadToolbarActivator:key.keyboard.x
[19:42:02] [Client thread/WARN]: Skipping bad option: key_key.swapHands:key.keyboard.f
[19:42:02] [Client thread/INFO]: LWJGL Version: 2.9.4
[19:42:03] [Client thread/INFO]: Reloading ResourceManager: Default
[19:42:03] [Sound Library Loader/INFO]: Starting up SoundSystem...
[19:42:04] [Thread-3/INFO]: Initializing LWJGL OpenAL
[19:42:04] [Thread-3/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[19:42:04] [Thread-3/INFO]: OpenAL initialized.
[19:42:04] [Sound Library Loader/INFO]: Sound engine started
[19:42:08] [Client thread/INFO]: Created: 1024x512 textures-atlas
[19:42:10] [Client thread/INFO]: Narrator library for x64 successfully loaded
[19:43:08] [Client thread/INFO]: Stopping!
[19:43:08] [Client thread/INFO]: SoundSystem shutting down...
[19:43:08] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com

**Comment by gnomed-by-steve** [comment]
Sorry, incorrect log. Here's the real one:
[2018-12-15-2.log](https://github.com/FlansMods/FlansMod/files/2692352/2018-12-15-2.log)

**Comment by ChrisLane** [comment]
I can see that you're using the "CANADIAN Content Pack" and must not have gotten round to trying without content packs.

I was able to reproduce the issue and removing the content pack fixed the crash. The content pack states that it's for 1.7.10

**Comment by gnomed-by-steve** [comment]
Thank you.
